import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>IPDC - Banking Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      
       
          <div className="md:absolute md:right-0 md:top-0 z-5  ">
            <img src="/Big.png" className='md:h-[600px] md:w-[800px] mt-[30px] md:mt-0 '/>
          </div>

          <div className='md:ml-[70px] md:mt-[80px] px-3 md:px-0 z-10'>
            <h1 className="font-bold text-6xl mb-[30px]">Chase Your<br/> Dream With Us</h1>
            <p className=" md:w-[390px]">The harder you work for something the greater you will feel when you acheive it</p>
            <div className="flex gap-[30px] mt-[50px]">
              <button className="bg-[#ED017F] p-2 shadow text-white text-sm rounded">APPLY ONLINE</button>  <button className='p-2 border border-2-[#ED017F] bg-transparent text-sm text-[#ED017F]' style={{border:'1px solid #ED017F'}}>LOAN CALCULATOR</button>
            </div>

            <div className="md:mt-[120px] mt-[50px]">
          <img src="/Frame 7.png" className='w-[200px]'/>
          </div>
          </div>

         <div className='md:mt-[200px]  flex flex-col items-center justify-center gap-[30px] mt-[100px]'>
          <div>
            <h1 className="font-bold text-3xl mb-[30px] text-center">Creating Extraordinary Customers Experience</h1>
            <p className="text-center text-sm md:w-[600px]">The harder you work for something the greater you will
               feel when you acheive itThe harder you work for 
               will feel when you acheive it

            </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 md:gap-[100px] gap-[30px]">
            <div className="md:w-[200px] w-[300px]">
              <img src="/Object Ungroup.png"/>
              <div>
                <h2 className="font-bold">Diversity</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Cube.png"/>
              <div>
                <h2 className="font-bold">Integrity</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Rocket.png"/>
              <div>
                <h2 className="font-bold">Technology</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Scenery.png"/>
              <div>
                <h2 className="font-bold">Digital</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Bag.png"/>
              <div>
                <h2 className="font-bold">Corporate</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Bag.png"/>
              <div>
                <h2 className="font-bold">Collaboration</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/Circle Layer.png"/>
              <div>
                <h2 className="font-bold">Demonstrate</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>

            <div  className="md:w-[200px] w-[300px]">
              <img src="/User Arrows.png"/>
              <div>
                <h2 className="font-bold">Teamwork</h2>
                <p>Setting the standard for the best corporate citizenship in the communities we work</p>
              </div>
            </div>
          </div>


         </div>

         <div className="bg-[#FEF9FC] h-[300px] mt-[40px] flex flex-col items-center justify-center">
          <h1 lassName="py-4">BUSINESS PARTNERS</h1>
          <div className="grid grid-cols-2 md:grid-cols-4 md:gap-[40px] mt-[30px]">
            <img src="/Frame 1.png"/>
            <img src="/Frame 13.png"/>
            <img src="/Frame 14.png"/>
            <img src="/Frame 15.png"/>

          </div>

         </div>

         <div className="flex gap-[100px] items-center flex-col-reverse md:flex-row">
          <img src="/Picture.png" className="h-[450px] w-[600px]"/>
          <div className='md:w-[400px] mt-[90px] px-3'>
            <h2 className="font-bold text-2xl mb-[20px]">IPDC AT A GLANCE</h2>
            <p className="text-sm">IPDC Finance Limited(previously known as Industrial Promotion and Development Company of Banglasdesh Limited)
              is the first private sector finanacial institution of the country established in 1918 by a distinguished group of shareholders namely France Corporation, USA, German investment
              and Development Company
            </p>
            <button className='text-[#ED017F] mt-[20px] font-bold'>Read More</button>
          </div>
         </div>


         <div className="bg-[#FEF9FC] md:h-[850px] mt-[0px] flex flex-col items-center justify-center p-4">
          <div className='py-4'>
            <h1 className='font-bold text-2xl text-center py-4'>OUR SERVICES</h1>
            <p className="text-sm text-center">IPDC Finance Limited(previously known as Industrial Promotion and Development Company of Banglasdesh </p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-[30px] mt-[30px] p-4">
            <div>
            <img src="/Image.png"/>
            <div className="flex items-center justify-between mt-[15px]">
            <h1 className='text-sm font-bold'>IPDC SAVING <br/>SCHEME</h1>
            <img src="/Arrow Circle Right.png"/>
            </div>
           
            </div>

            <div>
          
            <img src="/im.png"/>
            <div className="flex items-center justify-between mt-[15px]">
            <h1 className='text-sm font-bold'>IPDC PERSONAL <br/>LOAN</h1>
            <img src="/Arrow Circle Right.png"/></div>
            </div>

            <div>
            <img src="/Image.png"/>
            <div className="flex items-center justify-between mt-[15px]">
            <h1 className='text-sm font-bold'>IPDC SAVING <br/>SCHEME</h1>
            <img src="/Arrow Circle Right.png"/></div>
            </div>

            <div>
            <img src="/im.png"/>
            <div className="flex items-center justify-between mt-[15px]">
            <h1 className='text-sm font-bold'>IPDC AUTO <br/>LOAN</h1>
            <img src="/Arrow Circle Right.png"/></div>
            </div>
           
          </div>
         </div>
       
      

         <div className="bg-white md:h-[550px] mt-[0px] flex flex-col items-center justify-center p-4">
         <div className='py-4'>
            <h1 className='font-bold text-2xl text-center py-4'>Our best results for the year</h1>
            <p className="text-sm md:w-[450px] text-center">IPDC Finance Limited(previously known as Industrial Promotion and Development Company of Banglasdesh </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-[80px] mt-[30px]">
            <div>
              <h2 className='font-bold text-2xl text-[#ED017F]'>57.6bn</h2>
              <p className='text-sm'>LOAN PORTFOLIO</p>
            </div>

            <div>
              <h2 className='font-bold text-2xl'>0.95%</h2>
              <p className='text-sm'>CLASSIFIED LOAN <br/>PORTFOLIO</p>
            </div>

            <div>
              <h2 className='font-bold text-2xl'>388.5%</h2>
              <p className='text-sm'>CLASSIFIED LOAN <br/>COVERAGE</p>
            </div>

            <div>
              <h2 className='font-bold text-2xl'>50.4bn</h2>
              <p className='text-sm'>DEPOSIT</p>
            </div>

            <div>
              <h2 className='font-bold text-2xl'>6.1bn</h2>
              <p className='text-sm'>SHAREHOLDERS <br/>EQUITY</p>
            </div>

            <div>
              <h2 className='font-bold text-3xl'>18.51%</h2>
              <p className='text-sm'>CLASSIFIED LOAN<br/> PORTFOLIO</p>
            </div>

            <div>
              <h2 className='font-bold text-2xl'>8.5bn</h2>
              <p className='text-sm'>MARKET <br/>CAPITALIZATION</p>
            </div>
            <div>
              <h2 className='font-bold text-2xl'>AAA</h2>
              <p className='text-sm'>CREDIT RATING</p>
            </div>
          </div>
         </div>
     
         <div className="bg-[#FEF9FC] h-[350px] mt-[0px] flex flex-col items-center justify-center p-4">
         <div className='py-4'>
            <h1 className='font-bold text-2xl text-center py-4'>Newsletter</h1>
            <p className="text-sm md:w-[450px] text-center">IPDC Finance Limited(previously known as Industrial Promotion and Development  </p>
          </div>
          <div className='flex flex-col md:flex-row items-center gap-[20px]'>
            <input type="email" placeholder="Email" className='p-2 w-[300px] border border-2-gray'/>     <button className="bg-[#ED017F] p-2 shadow text-white text-sm rounded w-[280px] md:w-[150px]">SUBSCRIBE</button>
          </div>
         </div>
      

     
    </>
  )
}
